* Per-System Settings
#+BEGIN_SRC emacs-lisp
  (setq compile-command (getenv "COMPILE_COMMAND"))
#+END_SRC
* Package Management
Set up straight.el
#+BEGIN_SRC emacs-lisp
  (defvar bootstrap-version)
  (let ((bootstrap-file
         (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
        (bootstrap-version 5))
    (unless (file-exists-p bootstrap-file)
      (with-current-buffer
          (url-retrieve-synchronously
           "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
           'silent 'inhibit-cookies)
        (goto-char (point-max))
        (eval-print-last-sexp)))
    (load bootstrap-file nil 'nomessage))
#+END_SRC
Use use-package as a frontend for straight
#+BEGIN_SRC emacs-lisp
(straight-use-package 'use-package)
(setq straight-use-package-by-default t)
#+END_SRC
* Keybindings
Using ~bind-key*~ will force precedence over keybinds from a mode map.
#+BEGIN_SRC emacs-lisp
  (use-package bind-key)

  (bind-key* [C-return] 'calc)
  (bind-key* [f5] 'recompile)
  (bind-key [f11] 'toggle-frame-fullscreen)

  (bind-key "M-," 'xref-pop-marker-stack)
  (bind-key "M-." 'xref-find-definitions)
  (bind-key "M-;" 'comment-line)
  (bind-key "M-/" 'company-complete)
  (bind-key "M-n" (lambda() (interactive) (scroll-up 1)))
  (bind-key "M-o" 'next-multiframe-window)
  (bind-key "M-O" 'previous-multiframe-window)
  (bind-key "M-p" (lambda() (interactive) (scroll-down 1)))
  (bind-key "M-z" 'avy-zap-to-char-dwim)

  (bind-key "C-c SPC" 'avy-goto-line)
  (bind-key "C-c ." 'eglot-code-actions)
  (bind-key "C-c d" 'delete-horizontal-space)
  (bind-key "C-c f" 'counsel-git)
  (bind-key "C-c g" 'counsel-rg)
  (bind-key "C-c h" 'eglot-help-at-point)
  (bind-key "C-c j" 'counsel-mark-ring)
  (bind-key "C-c m" 'mc/edit-lines)
  (bind-key "C-c o" 'projectile-find-other-file)
  (bind-key "C-c r" 'replace-string)
  (bind-key "C-c s" 'swiper-all)
  (bind-key "C-c x" 'multi-vterm-next)
  (bind-key "C-c z" 'avy-zap-to-char)

  (bind-key "C-c C-SPC" 'avy-goto-char-2)
  (bind-key* "C-c C-f" 'counsel-fzf)
  (bind-key "C-c C-r" 'query-replace)
  (bind-key "C-c C-x" 'multi-vterm)

  (bind-key "C-x g" 'magit-status)
  (bind-key "C-x C-b" 'ibuffer)

  (bind-key "C-r" 'swiper)
  (bind-key "C-s" 'swiper)
#+END_SRC

* Emacs System Settings
For profiling startup time
#+BEGIN_SRC emacs-lisp
  (use-package esup
    :commands (esup)
    :config (setq esup-user-init-file (file-truename "~/emacs/init.el")))
#+END_SRC
Confirm quit
#+BEGIN_SRC emacs-lisp
(setq confirm-kill-emacs 'y-or-n-p)
#+END_SRC
Stop custom from cluttering my init file
#+BEGIN_SRC emacs-lisp
  (setq custom-file (expand-file-name "custom.el" user-emacs-directory))
  (when (file-exists-p custom-file)
    (load custom-file))
#+END_SRC
Store backups in os tmp instead of cluttering working dir.
#+BEGIN_SRC emacs-lisp
  (setq backup-directory-alist
        `((".*" . ,temporary-file-directory)))
  (setq auto-save-file-name-transforms
        `((".*" ,temporary-file-directory t)))
#+END_SRC

* Ivy
#+BEGIN_SRC emacs-lisp
  (use-package ivy
    :config
    (ivy-mode 1)
    (setq ivy-use-virtual-buffers t)
    (setq enable-recursive-minibuffers t)
    (setq ivy-use-selectable-prompt t))
  (use-package counsel
    :config
    (counsel-mode 1))
  (use-package swiper)
  (use-package all-the-icons-ivy-rich
    :ensure t
    :init (all-the-icons-ivy-rich-mode 1))
  (use-package ivy-rich
    :config
    (setcdr (assq t ivy-format-functions-alist) #'ivy-format-function-line)
    (ivy-rich-mode 1))
#+END_SRC
* Terminal
Unlimited scrollback
#+BEGIN_SRC emacs-lisp
  (setq term-buffer-maximum-size 0)
#+END_SRC
Vterm is a term mode that integrates really nicely with emacs keybindings
#+BEGIN_SRC emacs-lisp
  (use-package vterm
    :config
    (setq vterm-max-scrollback 100000))
#+END_SRC
For managing multiple vterm buffers
#+BEGIN_SRC emacs-lisp
  (use-package multi-vterm)
#+END_SRC
* Appearance
The main theme
#+BEGIN_SRC emacs-lisp
  (use-package zenburn-theme
    :config
    (load-theme 'zenburn t))
#+END_SRC
Icons used by doom-modeline
Scale factor helps to not increase modeline size (default is 1.2 for some reason)
#+BEGIN_SRC emacs-lisp
  (use-package all-the-icons
    :config
    (setq all-the-icons-scale-factor 1.0))
  (use-package all-the-icons-dired
    :config
    (add-hook 'dired-mode-hook 'all-the-icons-dired-mode))
#+END_SRC
Modeline theme. Disable major mode icon since it gets uncentered with 1.0 scale factor set above.
#+BEGIN_SRC emacs-lisp
  (use-package doom-modeline
    :init (doom-modeline-mode 1)
    :config
    (setq doom-modeline-major-mode-icon nil))
#+END_SRC
Anzu shows x/n position during isearch
#+BEGIN_SRC emacs-lisp
  (use-package anzu
    :config
    (setq anzu-mode-lighter "")
    (setq anzu-cons-mode-line-p nil)
    (global-anzu-mode +1))
#+END_SRC
Flash modeline instead of bell sound
#+BEGIN_SRC emacs-lisp
  (setq ring-bell-function
        (lambda ()
          (let ((orig-fg (face-foreground 'mode-line)))
            (set-face-foreground 'mode-line "#555555")
            (run-with-idle-timer 0.1 nil
                                 (lambda (fg) (set-face-foreground 'mode-line fg))
                                 orig-fg))))
#+END_SRC
Disable startup screen and UI elements
#+BEGIN_SRC emacs-lisp
  (setq inhibit-startup-message t)
  (tool-bar-mode -1)
  (scroll-bar-mode -1)
  (menu-bar-mode -1)
#+END_SRC
Show line numbers in code buffers. Turning it on globally slows down terminal buffers and other fast-scrolling buffers.
#+BEGIN_SRC emacs-lisp
  (add-hook 'prog-mode-hook 'display-line-numbers-mode)
#+END_SRC
Highlight matching parens, and use same colors for matching pairs.
#+BEGIN_SRC emacs-lisp
  (show-paren-mode 1)
  (use-package rainbow-delimiters
    :config
    (add-hook 'prog-mode-hook 'rainbow-delimiters-mode))
#+END_SRC
* File Management
For opening files as sudo
#+BEGIN_SRC emacs-lisp
  (use-package sudo-edit)
#+END_SRC
* Buffers
Auto-update buffers on file change
#+BEGIN_SRC emacs-lisp
  (global-auto-revert-mode 1)
#+END_SRC
Don't auto-split vertically
#+BEGIN_SRC emacs-lisp
  (setq split-height-threshold nil)
#+END_SRC
Scroll compilation buffer until first error
#+BEGIN_SRC emacs-lisp
  (setq compilation-scroll-output 'first-error)
#+END_SRC
Save window configs
#+BEGIN_SRC emacs-lisp
  (winner-mode)
#+END_SRC
Clean up trailing whtitespace on edited lines on save
#+BEGIN_SRC emacs-lisp
  (use-package ws-butler
    :config
    (ws-butler-global-mode))
#+END_SRC
DIsplay terminal colors correctly in compilation buffer
#+BEGIN_SRC emacs-lisp
  (require 'ansi-color)
  (defun endless/colorize-compilation ()
    "Colorize from `compilation-filter-start' to `point'."
    (let ((inhibit-read-only t))
      (ansi-color-apply-on-region
       compilation-filter-start (point))))

  (add-hook 'compilation-filter-hook
            #'endless/colorize-compilation)
#+END_SRC
* Org Mode
#+BEGIN_SRC emacs-lisp
  (use-package org)
#+END_SRC
This makes indentation inside src blocks work
#+BEGIN_SRC emacs-lisp
  (setq org-src-tab-acts-natively t)
#+END_SRC
Word wrap
#+BEGIN_SRC emacs-lisp
(setq org-startup-truncated nil)
(add-hook 'org-mode-hook 'toggle-word-wrap)
#+END_SRC
Automatic indentation and hide prefix asterisks
#+BEGIN_SRC emacs-lisp
  (add-hook 'org-mode-hook 'org-indent-mode)
#+END_SRC
For publishing org to hugo
#+BEGIN_SRC emacs-lisp
  (use-package ox-hugo
    :after ox)
#+END_SRC
* Project Management
Projectile
#+BEGIN_SRC emacs-lisp
  (use-package projectile
    :config
    (projectile-mode 1)
    (setq projectile-completion-system 'ivy)
    (define-key projectile-mode-map (kbd "C-c p") 'projectile-command-map))
#+END_SRC
* Version Control
Git porcelain
#+BEGIN_SRC emacs-lisp
  (use-package magit
    :config
    (setq magit-log-arguments (quote ("--graph" "--color" "--decorate" "-n100")))
    (setq magit-diff-arguments (quote ("--ignore-space-change" "--ignore-all-space" "--no-ext-diff" "--stat"))))
#+END_SRC
Show git status per-line in the fringe
#+BEGIN_SRC emacs-lisp
  (use-package git-gutter-fringe
    :config
    (global-git-gutter-mode))
#+END_SRC
* General Editing
Turned off undo-tree history since the files get humongous. Should just figure out how to limit size
#+BEGIN_SRC emacs-lisp
  (setq-default indent-tabs-mode nil)
  (global-subword-mode 1)
  (use-package avy)
  (use-package avy-zap)
  (use-package multiple-cursors)
  (use-package undo-tree
    :config
    (global-undo-tree-mode)
    (setq undo-tree-auto-save-history nil)
    (setq undo-tree-history-directory-alist
          (quote (("" . "~/.emacs.d/undo_hist")))))
#+END_SRC
* Completion
#+BEGIN_SRC emacs-lisp
  (use-package company
    :config
    (global-company-mode)
    (define-key company-active-map (kbd "M-n") nil)
    (define-key company-active-map (kbd "M-p") nil)
    (define-key company-active-map (kbd "C-n") #'company-select-next)
    (define-key company-active-map (kbd "C-p") #'company-select-previous))
#+END_SRC
yasnippet allows eglot to provide templated completions
#+BEGIN_SRC emacs-lisp
  (use-package yasnippet
    :config
    (yas-global-mode 1))
#+END_SRC
* C++ Development
#+BEGIN_SRC emacs-lisp
  (add-to-list 'auto-mode-alist '("\\.h\\'" . c++-mode))
  (add-to-list 'auto-mode-alist '("\\.cl\\'" . c++-mode))
  (add-to-list 'auto-mode-alist '("\\.inl\\'" . c++-mode))
#+END_SRC
Clang-format on save
#+BEGIN_SRC emacs-lisp
  (add-hook 'before-save-hook
            (lambda ()
              (when (member major-mode '(c-mode c++-mode glsl-mode))
                (progn
                  (when (locate-dominating-file "." ".clang-format")
                    (clang-format-buffer))
                  ;; Return nil, to continue saving.
                  nil))))
#+END_SRC
No indents for macros, opening parens, or namespaces
#+BEGIN_SRC emacs-lisp
  (c-set-offset (quote cpp-macro) 0 nil)
  (c-set-offset 'substatement-open 0)
  (c-set-offset 'innamespace 0)
#+END_SRC
More indentation settings
#+BEGIN_SRC emacs-lisp
  (add-hook 'c++-mode-hook
            (setq c-default-style "linux"
                  c-basic-offset 2
                  tab-width 2
                  indent-tabs-mode nil))
#+END_SRC
Use company-capf to talk to eglot
#+BEGIN_SRC emacs-lisp
  (add-hook 'c++-mode-hook
            (lambda ()
              (set (make-local-variable 'company-backends)
                   '(company-capf))))
#+END_SRC
Other packages
#+BEGIN_SRC emacs-lisp
  (use-package clang-format)
#+END_SRC
* Static Analysis
Shellcheck for shell scripts
#+BEGIN_SRC emacs-lisp
  (use-package flymake-shellcheck
    :commands flymake-shellcheck-load
    :init
    (add-hook 'sh-mode-hook 'flymake-shellcheck-load)
    (add-hook 'sh-mode-hook 'flymake-mode))
#+END_SRC
Eglot for C++ with ccls and python with pyls
#+BEGIN_SRC emacs-lisp
  (use-package eglot
        :config
        (add-to-list 'eglot-server-programs '((c++-mode c-mode) "ccls" "-init={\"clang\": {\"excludeArgs\": [\"-fopenmp=libomp\"]}}"))
        (add-to-list 'eglot-server-programs '((python-mode) "pyls"))
        (add-hook 'c-mode-hook 'eglot-ensure)
        (add-hook 'c++-mode-hook 'eglot-ensure)
        (add-hook 'python-mode-hook 'eglot-ensure))

  ; eglot+straight fix: https://github.com/hlissner/doom-emacs/issues/3269
  (defun project-root (project)
      (car (project-roots project)))
#+END_SRC
Dumb jump for rg-based jump-to-definition
#+BEGIN_SRC emacs-lisp
  (use-package dumb-jump
    :config
    (dumb-jump-mode)
    (setq dumb-jump-selector 'ivy))
#+END_SRC
* CMake
#+BEGIN_SRC emacs-lisp
  (use-package cmake-mode
    :config
    (setq cmake-tab-width 4))
#+END_SRC
